In [1]:
price=10
price=20
rating=4.0
name='Ritika'
is_publish = True
print(price,rating,name,is_publish)

20 4.0 Ritika True


In [2]:
patient_name = "John Smith"
Age = 20
Is_NewPatient = True

<li> patient_name = "John Smith" sets the name as a string </li>
<li> Age = 20 stores an integer value</li>
<li> Is_NewPatient = True is a boolean value </li>

In [3]:
patient_name= input("What is your name? ")

What is your name?  Ritika


In [12]:
print(patient_name)

Ritika Maheshwari


To club Age input and display together

In [5]:
age = input("What is your age? ")
print(age)

What is your age?  32


32


In [6]:
hello = input("What is your name?")
print("Hi", hello)

What is your name? Damien


Hi Damien


In [7]:
hello = input("What is your name?")
print("Hi"+hello)

What is your name? Jack


HiJack


In [8]:
hello = input("What is your name?")
print("Hi" + hello)

What is your name? John


HiJohn


In [9]:
hello = input("What is your name?")
print("Hi "+hello)

What is your name? Joe


Hi Joe


> WAP to ask two questions to the user - Person's name and favorite color. Then print a message like - Mosh likes blue

In [6]:
name = input("What is your name? ")
color = input("What is your favorite color? ")
print (name +" likes "+color)

What is your name?  Ritika
What is your favorite color?  Black


Ritika likes Black


> WAP to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.


In [2]:
hours = input("Enter the number of hours")
rate = input("Enter the rate per hour")
grosspay = float(hours)*float(rate)
if(int(hours) > 40):
    additionalhours = int(hours) - 40
    grosspay = (0.5*float(rate)*float(additionalhours)) + grosspay 
print("Gross Pay: ",grosspay)

Enter the number of hours 45
Enter the rate per hour 10.5


Gross Pay:  498.75


> WAP the previous program with try and except

In [1]:
hours = input("Enter the number of hours")
rate = input("Enter the rate per hour")
try:
    grosspay = float(hours)*float(rate)
    if(int(hours) > 40):
        additionalhours = int(hours) - 40
        grosspay = (0.5*float(rate)*float(additionalhours)) + grosspay
    print("Gross Pay: ",grosspay)
except:
    print("Enter Integer numbers")
    quit()

Enter the number of hours 45
Enter the rate per hour ten point 5


Enter Integer numbers


>  WAP to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
 '>= 0.9 A
'>= 0.8 B
'>= 0.7 C
'>= 0.6 D
'< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [14]:
score = input("Enter a score between 0.0 and 1.0")
fscore = float(score)
#print(fscore)
if fscore <= 1.0:
    if fscore >= 0.9: print("A")
    elif fscore >= 0.8: print("B")
    elif fscore >= 0.7: print("C")
    elif fscore >= 0.6: print("D")
    else: print("F")
else: print("Score out of range")

Enter a score between 0.0 and 1.0 0.2


F


In [9]:
x=50+2j
print(x, x.real, x.imag)

(50+2j) 50.0 2.0


In [13]:
listname = ["Ritika", 8767255539, "Rahul", 9892368666]

In [15]:
print (listname)

['Ritika', 8767255539, 'Rahul', 9892368666]


In [18]:
x = 5
y = x
x=x+y
print(x+y)
print(x)
print (y)

15
10
5


In [19]:
7//2

3

In [21]:
7/2

3.5

In [39]:
"a"!="A" or "b"<"a"

True

In [46]:
a = 10
print(a)
a*=12
print(a)

10
120


In [53]:
x=int(input("Enter data"))

Enter data 20


In [54]:
print (x)

20


> 4.6 WAP to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

In [22]:
def computepay(fh,fr):
    grosspay = float(fh)*fr
    if(fh>40):
        diffinhrs = int(fh) - 40
        grosspay = grosspay+(0.5*diffinhrs*(fr))
    return grosspay

hrs = input("Enter Hours:")
rate = float((input("Enter Rate:")))
gpay = computepay (fhrs,rate)
print("Pay",gpay)

Enter Hours: 45
Enter Rate: 10.5


Pay 498.75


In [1]:
smallest_so_far = -1
for the_num in [9, 41, 12, 3, 74, 15] :
   if the_num < smallest_so_far :
      smallest_so_far = the_num
print(smallest_so_far)

-1


> WAP that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.


In [7]:
largest_so_far = -1
smallest_so_far = None
counter = 0
while True:
    num = input("Enter a number:")
    if (num == 'done'):
        break
    else:
        try:
            inum = int(num)
        except:
            print("Invalid Input")
            continue        
    if inum > largest_so_far:
        largest_so_far = inum
    if smallest_so_far is None:
        smallest_so_far = inum
    elif inum < smallest_so_far:
        smallest_so_far = inum
print("Maximum is", largest_so_far)
print("Minimum is", smallest_so_far)

Enter a number: 7
Enter a number: 2
Enter a number: bob


Invalid Input


Enter a number: 10
Enter a number: 4
Enter a number: done


Maximum is 10
Minimum is 2


#### String Slicing and Indexing

In [1]:
string = "Ritika Rahul Jain"

In [2]:
string[4]

'k'

> WAP to count the number of vowels, consonants and spaces in a user entered string

In [10]:
string_value = input("Enter a string")
length = len(string_value)
#print(length)
i=length - 1
vowelcounter = spacecounter = 0
while i>0:
    if string_value[i] in ['a','e','i','o','u']:
        vowelcounter = vowelcounter + 1
    elif string_value[i] is ' ':
        spacecounter = spacecounter + 1
    i = i-1

print("Number of Vowels in the entered string is", vowelcounter)
print("Number of Consonants in the entered string is",length-spacecounter-vowelcounter)
print("Number of spaces in the entered string is", spacecounter)

Enter a string hello world! My name is Ritika


Number of Vowels in the entered string is 9
Number of Consonants in the entered string is 16
Number of spaces in the entered string is 5


In [15]:
name = "RAHUL RITIKA"

In [17]:
name[6:]

'RITIKA'

In [18]:
name[:5]

'RAHUL'

In [21]:
name[:3]

'RAH'

In [22]:
name[9:]

'IKA'

In [23]:
name[::-1]

'AKITIR LUHAR'

In [24]:
'Hello World'[8]

'r'

In [25]:
'tinker'[1:4]

'ink'

In [3]:
x = "I17143: [ON HOLD] India On-Soil Deployment - 2020-2021 Harness Components"

In [4]:
x.upper()

'I17143: [ON HOLD] INDIA ON-SOIL DEPLOYMENT - 2020-2021 HARNESS COMPONENTS'

In [5]:
x.upper

<function str.upper>

In [6]:
x.split()

['I17143:',
 '[ON',
 'HOLD]',
 'India',
 'On-Soil',
 'Deployment',
 '-',
 '2020-2021',
 'Harness',
 'Components']

In [10]:
x.split("i")

['I17143: [ON HOLD] Ind',
 'a On-So',
 'l Deployment - 2020-2021 Harness Components']

In [11]:
x.split()

['I17143:',
 '[ON',
 'HOLD]',
 'India',
 'On-Soil',
 'Deployment',
 '-',
 '2020-2021',
 'Harness',
 'Components']

In [12]:
x.split

<function str.split>

In [15]:
str.split

<method 'split' of 'str' objects>

> WAP to enter a user entered sentence and switch positions of the 2nd and 4th words

In [44]:
user_sentence = input("Enter a Sentence")
split_sentence = user_sentence.split()
list_len = len(split_sentence)
if(list_len<4):
    print("Input a string greater than 4 words")
else:
    print("Sentence after switching 2nd and 4th words is - {a} {d} {c} {b}".format(a=split_sentence[0],b=split_sentence[1],c=split_sentence[2],d=split_sentence[3]), " ".join(tuple(split_sentence[4:])))
          

Enter a Sentence the fox brown quick jumped over the lazy dog


Sentence after switching 2nd and 4th words is - the quick brown fox jumped over the lazy dog


> WAP to calculate the area of the circle for a given radius upto 3 decimals

In [49]:
radius = float(input("Enter the radius of the circle"))
pi = 22/7
area = pi*radius**2
print("The area of the circle with radius as {r} is {a:1.3f}".format(r=radius, a=area))

Enter the radius of the circle 5


The area of the circle with radius as 5.0 is 78.571


> WAP to display a grocery list of 5 items in a tabular format

In [75]:
print("{0:^25}|{1:^15}".format("Items","Price"))
print("{0:<25}|{1:>15}".format("Lady Finger "'(Organic)'"","25 INR"))
print("{0:<25}|{1:>15}".format("Apples Kashmir","160 INR"))
print("{0:<25}|{1:>15}".format("Pears"," 250 INR"))
print("{0:<25}|{1:>15}".format("Watermelon","567 INR"))
print("{0:<25}|{1:>15}".format("Dummy","0 INR"))

          Items          |     Price     
Lady Finger (Organic)    |         25 INR
Apples Kashmir           |        160 INR
Pears                    |        250 INR
Watermelon               |        567 INR
Dummy                    |          0 INR


> WAP to print the users name as a f-string

In [81]:
name = input("Enter your name")
print(f"Welcome to my world {name!r}")

Enter your name ruti


Welcome to my world 'ruti'


In [79]:
'{} rules!'.format('Python')

'Python rules!'

In [4]:
mydaydictionary = {"day1":"Sunday","day2":"Monday","day3":"Tuesday","day4":"Thursday" }

In [5]:
mydaydictionary

{'day1': 'Sunday', 'day2': 'Monday', 'day3': 'Tuesday', 'day4': 'Thursday'}

In [23]:
mydaydictionary2 = {"day1":1,"day2":2,"day3":3,"day4":4}

In [24]:
mydaydictionary2["day5"] = 5

In [25]:
mydaydictionary2

{'day1': 1, 'day2': 2, 'day3': 3, 'day4': 4, 'day5': 5}

In [8]:
set("Mississippi")

{'M', 'i', 'p', 's'}

In [9]:
t = (1,2,5,4,3,0)

In [10]:
t

(1, 2, 5, 4, 3, 0)

In [12]:
t.count(1)

1

In [15]:
t.index(3)

4

In [16]:
set([1,1,2,3])

{1, 2, 3}

> WAP to count the number of characters in a static string, use Dictionary to store the characters

In [43]:
string = "Hello World!"
i = len(string) - 1
print(i,string[i])
dictionary = {}
print(dictionary.items())
while i> -1:
    if string[i] in dictionary:
        dictionary[string[i]] = dictionary.get(string[i])+1
        #print("dictionary value from if",dictionary.items())
    else:
        dictionary[string[i]] = 1
        #print("dictionary value from else",dictionary.items())
    i = i-1
print(dictionary)

11 !
dict_items([])
{'!': 1, 'd': 1, 'l': 3, 'r': 1, 'o': 2, 'W': 1, ' ': 1, 'e': 1, 'H': 1}


In [125]:
%%writefile myfile.txt
this is a dummy file
second line

Overwriting myfile.txt


In [58]:
myfile = open("myfile.txt")

In [52]:
myfile2 = open("nofile.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'nofile.txt'

In [53]:
pwd

'/resources/Python Tutorial'

In [54]:
cd Python_Programs/

/resources/Python Tutorial/Python_Programs


In [66]:
myfile.seek(0)

0

In [67]:
contents = myfile.read()

In [68]:
contents

'this is a dummy file\nsecond line\n'

In [72]:
myfile.seek(0)

0

In [73]:
myfile.readlines()

['this is a dummy file\n', 'second line\n']

In [74]:
pwd

'/resources/Python Tutorial/Python_Programs'

In [75]:
myfile.close()

In [81]:
myfile = open("myfile.txt")

In [82]:
with open("myfile.txt") as my_newfile:
    content = my_newfile.read()

In [83]:
content

'this is a dummy file\nsecond line\n'

In [84]:
myfile.close()

In [86]:
my_newfile.read()

ValueError: I/O operation on closed file.

> WAP to count the number of characters from the file myfile.txt, use Dictionary to store the characters

In [134]:
with open("myfile.txt",mode = 'r+') as openedfile:
    string = openedfile.read()
    print(string)
    i = len(string) - 1
    dictionary = {}
    print(dictionary.items())
    while i> -1:
        if string[i] in dictionary: 
            dictionary[string[i]] = dictionary.get(string[i])+1
        else: 
            dictionary[string[i]] = 1
        i = i-1
    print(dictionary)
with open("myfile.txt",mode = "a") as openedfile:
    openedfile.write(str(dictionary))

this is a dummy file
second line
{'\n': 2, 'e': 3, 'n': 2, 'i': 4, 'l': 2, ' ': 5, 'd': 2, 'o': 1, 'c': 1, 's': 3, 'f': 1, 'y': 1, 'm': 2, 'u': 1, 'a': 1, 'h': 1, 't': 1}
dict_items([])
{'}': 1, '1': 8, ' ': 39, ':': 17, "'": 34, 't': 2, ',': 16, 'h': 2, 'a': 2, 'u': 2, '2': 5, 'm': 3, 'y': 2, 'f': 2, '3': 2, 's': 4, 'c': 2, 'o': 2, 'd': 3, '5': 1, 'l': 3, '4': 1, 'i': 5, 'n': 4, 'e': 4, '\\': 1, '{': 1, '\n': 2}


In [138]:
print(open("myfile.txt").read())

this is a dummy file
second line
{'\n': 2, 'e': 3, 'n': 2, 'i': 4, 'l': 2, ' ': 5, 'd': 2, 'o': 1, 'c': 1, 's': 3, 'f': 1, 'y': 1, 'm': 2, 'u': 1, 'a': 1, 'h': 1, 't': 1}{'}': 1, '1': 8, ' ': 39, ':': 17, "'": 34, 't': 2, ',': 16, 'h': 2, 'a': 2, 'u': 2, '2': 5, 'm': 3, 'y': 2, 'f': 2, '3': 2, 's': 4, 'c': 2, 'o': 2, 'd': 3, '5': 1, 'l': 3, '4': 1, 'i': 5, 'n': 4, 'e': 4, '\\': 1, '{': 1, '\n': 2}


> WAP that opens a file names `test.txt`, writes `'Hello World'` to the file, then closes it.

In [140]:
with open("test2.txt",mode='w') as file1:
    file1.write("Hello World")

In [141]:
myfile = open("test.txt",mode='w')
myfile.write("Hello World")
myfile.close()